#!/bin/bash

cd /tmp
wget https://gnubee-git.github.io/debian/modules.`uname -r`.tar.gz
mkdir -p /lib/modules/`uname -r`
cd /lib/modules/`uname -r`
tar xvzf /tmp/modules.`uname -r`.tar.gz
depmod -a

echo "deb https://gnubee-git.github.io/omv/ erasmus main" > /etc/apt/sources.list.d/omv.list
apt-get update
apt-get install openmediavault -y --force-yes

locale-gen "en_US.UTF-8"
dpkg-reconfigure locales

omv-initsystem
